### ISSUE TITLE
Different results when retraining doozy dataset

### ISSUE THREAD

**Issue by maorp** [AljazBozic/NeuralGraph#3] opened 2021-07-07 09:52 UTC
Hi, i have retrained the graph model for doozy for about 600K from scratch. i get different results, somewhat worse vs the given checkpoint. the graph affinity changes on each frame and legs are sometimes connected, transforms are also different and mesh has some badly deformed parts (see below).
for deforming a source frame to target i use the same code as in surfaceConsistencyLoss. (see my fork: https://github.com/maorp/NeuralGraph/blob/maorp-transformCloud/node_sampler/loss.py)

retrained graph, legs connected:
![image](https://user-images.githubusercontent.com/11231999/124722452-bdb39380-df12-11eb-94f6-6fa652452787.png)

loss:
![image](https://user-images.githubusercontent.com/11231999/124723352-a3c68080-df13-11eb-841e-185cc9c681b8.png)

deforming frame 30 to 0:
![image](https://user-images.githubusercontent.com/11231999/124737669-d3c85080-df20-11eb-99ff-63167c0d1946.png)

**Comment by AljazBozic** [comment] 2021-07-13 07:44
Hi @maorp!

Thank you for trying the method out! I just added the dense tracking implementation that we used, to produce consistent coloring in the paper (you can check the updated viz.py file).

About the reproducibility, I just re-trained the network again on the doozy sequence (using latest code, to make sure nothing went wrong during code refactoring), and I got a correct looking result. It's strange that you're encountering issues, since I tried this sequence a lot of times before. While it's not really deterministic, since the order of the nodes can change, and some local connectivity can be different, I didn't experience the artifacts you show. 

Here is how the losses from my latest experiment look like:
![image](https://user-images.githubusercontent.com/10977736/125411293-0f9a6480-e3be-11eb-9944-fd3e93321c98.png)

What I notice is that your `UniqueNeighbor` loss doesn't converge to similar value as in my case. To make debugging easier, can you try fixing the random seed as I did in the latest experiment (in the updated train_graph.py version)?

Best,
Aljaz

**Comment by maorp** [comment] 2021-07-13 20:05
Hi, Thanks Aljaz, ill try with the new train_graph and update.

**Comment by AljazBozic** [comment] 2021-08-11 07:19
I'll close the issue for now, let me know if you have further questions.

Best,
Aljaz

**Closed as completed by AljazBozic** 2021-08-11 07:19 UTC
